dist: trusty
language: ocaml
cache:
  apt: true
  directories:
  - "$HOME/.opam"
  - "$HOME/Library/Caches/Homebrew"
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - OPAMYES=true
  matrix:
  - COQ="coq"
matrix:
  fast_finish: true
  allow_failures:
  - os: osx
os:
- linux
before_install: if [ $TRAVIS_OS_NAME = osx ]; then brew update; brew install --ignore-dependencies
  ocaml opam; fi
install:
- travis_wait opam init
- eval $(opam config env)
- ocamlc -v
- opam repo add coq-released https://coq.inria.fr/opam/released || true
- travis_wait opam install $COQ coq-ext-lib
- opam list
script:
- set -e
- make -j
